### ISSUE TITLE
EUL Indexer, PIDman, digitized books Prod

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/TheKeep#60]
Doug will need to know when the change will happen.

**Comment by libdgg** [comment]
Goal is to do the change Monday.

**Comment by jcrompton42** [comment]
eulindexer and digitizedbooks are done. 

Pidman is apparently more complicated. I have the following update:

The quick technique I used to migrate pidman_dev to AWS did not work for the production database.
 
I will need to use a more elaborate technique that is slower, but has never failed.
• I have taken a dump of on-prem pidman, so we have a consistent snapshot of the database as of 10:58:10 09/11/2023
• I need to open a Service Request to get the datasync file system mounted to the on-prem libdbmysqlprod1 server.
Once the datasync file system is mounted, I can migrate the dump and import the pidman data.
I am confident that I will be able to successfully complete your request with data from 9/11, but it may take hours-to-days to complete because I need assistance from the Systems team.

**Comment by libdgg** [comment]
ACTION:
Step1: Beth will ask Jim if a subsequent migration will be faster so we can minimize the data loss window.
Ask Jim to take another data dump immediately prior to migration.

Based on response of Step 1 then determine if we need to:
- Ask SCO to freeze on uploads
- Banner for uploads not available during X period
-

**Comment by jcrompton42** [comment]
Jim did another dump and transfer from 10:05am to 10:38 am during the all staff meeting, so I migrated to the new pidman and zo verified that all seems well.
